![](image.jpg)


Dive into the heart of data science with a project that combines healthcare insights and predictive analytics. As a Data Scientist at a top Health Insurance company, you have the opportunity to predict customer healthcare costs using the power of machine learning. Your insights will help tailor services and guide customers in planning their healthcare expenses more effectively.

## Dataset Summary

Meet your primary tool: the `insurance.csv` dataset. Packed with information on health insurance customers, this dataset is your key to unlocking patterns in healthcare costs. Here's what you need to know about the data you'll be working with:

## insurance.csv
| Column    | Data Type | Description                                                      |
|-----------|-----------|------------------------------------------------------------------|
| `age`       | int       | Age of the primary beneficiary.                                  |
| `sex`       | object    | Gender of the insurance contractor (male or female).             |
| `bmi`       | float     | Body mass index, a key indicator of body fat based on height and weight. |
| `children`  | int       | Number of dependents covered by the insurance plan.              |
| `smoker`    | object    | Indicates whether the beneficiary smokes (yes or no).            |
| `region`    | object    | The beneficiary's residential area in the US, divided into four regions. |
| `charges`   | float     | Individual medical costs billed by health insurance.             |



A bit of data cleaning is key to ensure the dataset is ready for modeling. Once your model is built using the `insurance.csv` dataset, the next step is to apply it to the `validation_dataset.csv`. This new dataset, similar to your training data minus the `charges` column, tests your model's accuracy and real-world utility by predicting costs for new customers.

## Let's Get Started!

This project is your playground for applying data science in a meaningful way, offering insights that have real-world applications. Ready to explore the data and uncover insights that could revolutionize healthcare planning? Let's begin this exciting journey!

In [95]:
# Re-run this cell
# Import required libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score

# Loading the insurance dataset
insurance_data_path = 'insurance.csv'
insurance = pd.read_csv(insurance_data_path)
insurance.head()

    age     sex     bmi  children smoker     region       charges
0  19.0  female  27.900       0.0    yes  southwest     16884.924
1  18.0    male  33.770       1.0     no  Southeast     1725.5523
2  28.0    male  33.000       3.0     no  southeast     $4449.462
3  33.0    male  22.705       0.0     no  northwest  $21984.47061
4  32.0    male  28.880       0.0     no  northwest    $3866.8552

In [96]:
insurance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1272 non-null   float64
 1   sex       1272 non-null   object
 2   bmi       1272 non-null   float64
 3   children  1272 non-null   float64
 4   smoker    1272 non-null   object
 5   region    1272 non-null   object
 6   charges   1284 non-null   object
dtypes: float64(3), object(4)
memory usage: 73.3+ KB

In [97]:
insurance.describe()

               age          bmi     children
count  1272.000000  1272.000000  1272.000000
mean     35.214623    30.560550     0.948899
std      22.478251     6.095573     1.303532
min     -64.000000    15.960000    -4.000000
25%      24.750000    26.180000     0.000000
50%      38.000000    30.210000     1.000000
75%      51.000000    34.485000     2.000000
max      64.000000    53.130000     5.000000

In [98]:
columns = insurance.columns
for column in columns:
    print(f"Unique values of column {column} are:")
    print(insurance[column].unique(), "\n")

Unique values of column age are:
[ 19.  18.  28.  33.  32. -31.  46.  37.  60.  25.  62.  23.  56. -27.
  52. -23.  30. -34.  59.  63.  55.  31.  22.  nan  26.  35.  24.  41.
  21.  48.  36.  40.  58.  34.  43.  64.  20.  61.  27.  53.  44.  57.
 -41.  45. -35.  54.  38.  29.  49.  47.  51.  42.  50. -44. -39. -28.
 -40.  39. -25. -52. -26. -47. -45. -57. -43. -50. -58. -56. -30. -51.
 -60. -37. -55. -64. -22. -36. -21. -18. -20. -19. -33.]

Unique values of column sex are:
['female' 'male' 'woman' 'F' 'man' nan 'M']

Unique values of column bmi are:
[27.9   33.77  33.    22.705 28.88  25.74  33.44  27.74  29.83  25.84
 26.22  26.29  34.4   39.82  42.13  24.6   30.78  23.845 40.3   35.3
 36.005 32.4   34.1      nan 28.025 27.72  23.085 32.775 17.385 36.3
 35.6   26.315 28.6   28.31  36.4   20.425 32.965 20.8   36.67  39.9
 26.6   36.63  21.78  37.3   38.665 34.77  24.53  35.625 28.    34.43
 28.69  36.955 31.825 31.68  22.88  37.335 27.36  33.66  24.7   25.935
 22.42  28.9   39.1   36.19  23.98  24.75  28.5   28.1   32.01  27.4
 34.01  35.53  39.805 26.885 38.285 37.62  41.23  34.8   22.895 31.16
 27.2   26.98  39.49  24.795 31.3   30.8   38.28  19.95  19.3   31.6
 30.115 29.92  27.5   28.4   30.875 27.94  35.09  33.63  29.7   35.72
 32.205 49.06  27.17  23.37  37.1   23.75  28.975 31.35  33.915 28.785
 28.3   37.4   17.765 34.7   26.505 22.04  35.9   25.555 28.05  25.175
 31.9   36.    32.49  25.3   29.735 38.83  30.495 37.73  37.43  24.13
 37.145 25.46  39.52  24.42  27.83  36.85  39.6   29.8   29.64  28.215
 37.    33.155 18.905 41.47  30.3   15.96  33.345 37.7   27.835 29.2
 28.595 26.41  30.69  41.895 30.9   32.2   32.11  31.57  26.2   30.59
 32.8   18.05  39.33  32.23  24.035 36.08  22.3   26.4   31.8   26.73
 23.1   23.21  33.7   33.25  24.64  33.88  38.06  41.91  31.635 36.195
 17.8   24.51  22.22  29.07  22.135 26.8   30.02  20.9   17.29  34.21
 25.365 40.15  24.415 25.2   26.84  24.32  42.35  19.8   32.395 30.2
 34.2   37.05  27.455 27.55  20.615 24.3   31.79  21.56  28.12  40.565
 27.645 31.2   26.62  48.07  36.765 33.4   45.54  28.82  22.99  27.7
 25.41  22.61  37.51  38.    33.33  34.865 35.86  31.4   25.27  40.945
 34.105 36.48  33.8   36.7   36.385 34.5   32.3   27.6   29.26  23.18
 25.6   35.245 43.89  20.79  30.5   21.7   21.89  32.015 30.4   21.09
 22.23  32.9   24.89  31.46  17.955 30.685 43.34  39.05  30.21  31.445
 19.855 31.02  38.17  20.6   47.52  20.4   24.31  23.6   21.12  30.03
 17.48  20.235 17.195 23.9   35.15  22.6   39.16  27.265 29.165 16.815
 26.9   33.11  31.73  46.75  29.45  32.68  33.5   43.01  36.52  26.695
 33.1   29.6   38.6   23.4   46.53  30.14  30.    28.38  28.7   33.82
 24.09  32.67  25.1   32.56  41.325 39.5   34.3   31.065 21.47  25.08
 43.4   25.7   27.93  39.2   26.03  30.25  28.93  35.7   35.31  31.
 44.22  26.07  25.8   39.425 40.48  38.9   47.41  35.435 46.7   46.2
 21.4   23.8   44.77  32.12  29.1   37.29  36.86  34.295 38.095 23.465
 45.43  23.65  20.7   28.27  35.91  29.    19.57  31.13  21.85  33.725
 29.48  32.6   37.525 23.655 37.8   29.37  19.    21.3   33.535 42.46
 38.95  36.1   29.3   39.7   38.19  42.4   34.96  42.68  35.2   31.54
 29.81  21.375 40.81  17.4   20.3   18.5   26.125 41.69  24.1   36.2
 40.185 35.75  39.27  34.87  44.745 29.545 23.54  40.47  40.66  36.6
 35.4   27.075 28.405 21.755 40.28  30.1   32.1   38.39  23.7   35.5
 29.15  27.    37.905 22.77  22.8   34.58  27.1   19.475 26.7   34.32
 41.14  35.97  22.515 41.8   31.92  26.18  42.24  26.51  35.815 36.575
 42.94  21.01  24.225 17.67  34.39  31.5   31.1   32.78  32.45  50.38
 47.6   25.4   29.9   43.7   24.86  28.8   29.5   29.04  44.    20.045
 40.26  35.1   29.355 32.34  39.8   24.605 33.99  28.2   25.    33.2
 23.2   20.1   32.5   37.18  46.09  39.93  35.8   31.255 18.335 42.9
 26.79  39.615 25.9   25.745 28.16  23.56  40.5   35.42  39.995 34.675
 20.52  23.275 36.29  32.7   19.19  24.985 20.13  23.32  45.32  34.6
 18.715 21.565 38.38  23.    37.07  42.655 21.66  29.59  32.    18.3
 47.74  22.1   19.095 38.94  31.24  29.925 20.35  25.85  42.75  18.6
 23.87  45.9   21.5   30.305 44.88  41.1   40.37  28.49  33.55  40.375
 27.28  17.86  33.3   39.14  21.945 24.97  23.94  34.485 21.8   23.3
 36.96  21.28  29.4   27.3   37.9   37.715 23.76  25.52  27.61  27.06
 39.4   34.9   22.    30.36  27.8   53.13  39.71  32.87  44.7   30.97 ]

Unique values of column children are:
[ 0.  1.  3.  2. nan -1.  4. -2.  5. -3. -4.]

Unique values of column smoker are:
['yes' 'no' nan]

Unique values of column region are:
['southwest' 'Southeast' 'southeast' 'northwest' 'Northwest' 'Northeast'
 'northeast' 'Southwest' nan]

Unique values of column charges are:
['16884.924' '1725.5523' '$4449.462' ... '$1629.8335' '2007.945'
 '29141.3603']

1. Correct the `sex` column values to standard format ('male', 'female')
2. Drop rows with missing values
3. Remove '$' from `charges` column
4. Change negative values of `children` column to 0
5. Drop negative `age` values
6. Convert `region` values to lowercase

In [99]:
insurance['sex'] = insurance['sex'].replace({'M': 'male', 'man': 'male', 'F': 'female', 'woman': 'female'})
insurance['charges'] = insurance['charges'].replace({'\$': ''}, regex=True).astype(float)
insurance = insurance[insurance["age"] > 0]
insurance["children"] = insurance["children"].apply(lambda x: max(x, 0))
insurance["region"] = insurance["region"].str.lower()

insurance.dropna(inplace=True)

In [100]:
for column in columns:
    print(f"Unique values of column {column} are:")
    print(insurance[column].unique(), "\n")

Unique values of column age are:
[19. 18. 28. 33. 32. 46. 37. 60. 25. 62. 23. 56. 52. 30. 59. 63. 55. 31.
 22. 26. 35. 24. 41. 48. 36. 40. 58. 34. 43. 64. 20. 61. 27. 53. 44. 57.
 21. 45. 54. 38. 29. 49. 47. 51. 42. 50. 39.]

Unique values of column sex are:
['female' 'male']

Unique values of column bmi are:
[27.9   33.77  33.    22.705 28.88  33.44  27.74  29.83  25.84  26.22
 26.29  34.4   39.82  24.6   30.78  40.3   35.3   36.005 32.4   34.1
 28.025 27.72  23.085 32.775 17.385 36.3   35.6   26.315 28.31  36.4
 20.425 32.965 20.8   36.67  39.9   26.6   36.63  21.78  37.3   38.665
 34.77  24.53  35.625 28.    34.43  28.69  36.955 31.825 31.68  37.335
 27.36  33.66  24.7   22.42  39.1   36.19  23.98  24.75  28.5   28.1
 32.01  27.4   34.01  35.53  26.885 38.285 37.62  41.23  34.8   22.895
 31.16  27.2   26.98  39.49  24.795 31.3   30.8   38.28  19.95  19.3
 31.6   30.115 29.92  27.5   28.4   30.875 27.94  35.09  33.63  29.7
 35.72  32.205 49.06  27.17  23.37  37.1   23.75  28.975 31.35  33.915
 28.785 28.3   37.4   17.765 34.7   26.505 22.04  35.9   25.555 28.05
 25.175 31.9   36.    32.49  25.3   29.735 38.83  30.495 37.73  37.43
 24.13  37.145 25.46  39.52  24.42  27.83  36.85  39.6   29.64  28.215
 37.    33.155 18.905 41.47  30.3   15.96  33.345 37.7   27.835 29.2
 28.9   28.595 26.41  41.895 30.9   32.2   32.11  31.57  26.2   25.74
 30.59  28.6   18.05  39.33  32.23  24.035 36.08  22.3   26.4   26.73
 23.1   23.21  33.7   24.64  33.88  38.06  41.91  31.635 36.195 17.8
 24.51  22.22  29.07  22.135 26.8   30.02  20.9   17.29  34.21  25.365
 40.15  24.415 25.2   26.84  24.32  19.8   32.395 30.2   34.2   37.05
 27.455 27.55  20.615 24.3   31.79  21.56  28.12  40.565 27.645 31.2
 26.62  48.07  36.765 33.4   28.82  22.99  27.7   25.41  22.61  37.51
 38.    33.33  34.865 35.86  31.4   25.27  40.945 34.105 36.48  33.8
 36.7   36.385 34.5   32.3   27.6   29.26  23.18  25.6   35.245 43.89
 20.79  30.5   21.7   21.89  32.015 30.4   21.09  22.23  32.9   24.89
 31.46  17.955 30.685 43.34  39.05  30.21  31.445 19.855 31.02  38.17
 20.6   20.4   24.31  23.6   21.12  30.03  17.48  20.235 17.195 35.15
 22.6   39.16  27.265 29.165 16.815 26.9   33.11  31.73  46.75  29.45
 32.68  33.5   43.01  36.52  26.695 29.6   38.6   23.4   46.53  30.14
 30.    25.935 28.38  28.7   33.82  24.09  32.67  29.8   25.1   32.56
 41.325 39.5   34.3   31.065 21.47  25.08  43.4   27.93  39.2   30.25
 28.93  35.7   35.31  31.    44.22  26.07  25.8   39.425 42.13  40.48
 38.9   47.41  35.435 46.7   46.2   21.4   23.8   32.12  29.1   37.29
 36.86  34.295 38.095 23.465 45.43  23.65  20.7   28.27  35.91  30.69
 19.57  31.13  21.85  33.725 29.48  23.655 37.8   29.37  19.    21.3
 33.535 26.03  42.46  38.95  36.1   29.3   38.19  42.4   34.96  31.54
 29.81  21.375 40.81  17.4   20.3   18.5   26.125 41.69  40.185 35.75
 39.27  44.745 29.545 23.54  40.47  35.4   27.075 28.405 21.755 40.28
 30.1   32.1   38.39  23.7   35.5   29.15  27.    22.77  22.8   34.58
 35.2   27.1   29.    39.7   19.475 26.7   41.14  35.97  22.515 41.8
 31.92  26.18  42.24  26.51  35.815 36.575 42.94  21.01  24.225 17.67
 33.1   34.39  31.5   31.1   32.78  32.45  50.38  24.1   23.845 47.6
 29.9   43.7   36.2   24.86  28.8   29.04  44.    20.045 40.26  29.355
 32.34  39.8   24.605 33.99  28.2   25.    33.2   23.2   32.5   37.18
 46.09  39.93  35.8   31.255 18.335 42.9   26.79  39.615 25.9   25.745
 34.32  28.16  23.56  40.5   35.42  39.995 34.675 20.52  23.275 36.29
 32.7   19.19  24.985 20.13  23.32  45.32  18.715 21.565 38.38  23.
 37.07  42.655 21.66  29.59  32.    18.3   47.74  22.1   19.095 38.94
 31.24  29.925 20.35  25.85  42.75  32.8   18.6   23.87  45.9   32.6
 21.5   44.88  41.1   40.37  28.49  33.55  40.375 27.28  17.86  33.3
 39.14  34.6   21.945 24.97  23.94  30.305 34.485 21.8   23.3   36.96
 21.28  29.4   27.3   37.9   37.715 25.52  27.06  39.4   22.    30.36
 53.13  39.71  32.87  44.7   30.97 ]

Unique values of column children are:
[0. 1. 3. 2. 4. 5.]

Unique values of column smoker are:
['yes' 'no']

Unique values of column region are:
['southwest' 'southeast' 'northwest' 'northeast']

Unique values of column charges are:
[16884.924   1725.5523  4449.462  ...  1629.8335  2007.945  29141.3603]

In [101]:
insurance.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [102]:
features = insurance.drop('charges', axis=1)
target = insurance['charges']

In [103]:
insurance.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1149 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1149 non-null   float64
 1   sex       1149 non-null   object
 2   bmi       1149 non-null   float64
 3   children  1149 non-null   float64
 4   smoker    1149 non-null   object
 5   region    1149 non-null   object
 6   charges   1149 non-null   float64
dtypes: float64(4), object(3)
memory usage: 71.8+ KB

In [104]:
categorical_features = ["sex", "smoker", "region"]
numerical_features = ["age", "bmi", "children"]

In [105]:
features_categorical = pd.get_dummies(features[categorical_features], drop_first=True)

In [106]:
features_final = pd.concat([features[numerical_features], features_categorical], axis=1)

In [107]:
scaler = StandardScaler()

In [108]:
features_scaled = scaler.fit_transform(features_final)

In [109]:
from sklearn.linear_model import LinearRegression

In [110]:
lin_model = LinearRegression()

In [111]:
from sklearn.pipeline import Pipeline

In [112]:
steps = [('scaler', scaler), ('lin_model', lin_model)]
insurance_pipeline = Pipeline(steps)

In [113]:
insurance_pipeline.fit(features_scaled, target)

mse_scores = -cross_val_score(insurance_pipeline, features_scaled, target, cv=5, scoring='neg_mean_squared_error')
r2_scores = cross_val_score(insurance_pipeline, features_scaled, target, cv=5, scoring='r2')
mean_mse = np.mean(mse_scores)
r2_score = np.mean(r2_scores)

In [114]:
print("Mean MSE:", mean_mse)
print("Mean R2:", r2_score)

Mean MSE: 37431001.52191915
Mean R2: 0.7450511466263761

In [115]:
# Predict on validation data
validation_data_path = 'validation_dataset.csv'
validation_data = pd.read_csv(validation_data_path)

# Ensure categorical variables are properly transformed
validation_data_processed = pd.get_dummies(validation_data, columns=['sex', 'smoker', 'region'], drop_first=True)

# Make predictions using the trained model
validation_predictions = insurance_pipeline.predict(validation_data_processed)

# Add predicted charges to the validation data
validation_data['predicted_charges'] = validation_predictions

# Adjust predictions to ensure minimum charge is $1000
validation_data.loc[validation_data['predicted_charges'] < 1000, 'predicted_charges'] = 1000

# Display the updated dataframe
validation_data.head()

    age     sex        bmi  children smoker     region  predicted_charges
0  18.0  female  24.090000       1.0     no  southeast      128624.195643
1  39.0    male  26.410000       0.0    yes  northeast      220740.537449
2  27.0    male  29.150000       0.0    yes  southeast      181357.588606
3  71.0    male  65.502135      13.0    yes  southeast      423490.687270
4  28.0    male  38.060000       0.0     no  southeast      193247.431989